version: "3"
services:
  tomcat:
    build: ./tomcat
    ports: 
      - 8090:8080
  nginx:
    build: ./nginx
    ports: 
      - 8080:8080
  jenkis:
    build: ./jenkins
    ports: 
      - 9090:9090
      - 50000:50000