apiVersion: v1
kind: Service
metadata:
  name: jenkins-expose-service
  namespace: backbase
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 32752
  selector:
    name: jenkins